config/routes.rb
Rails.application.routes.draw do
  get 'recipe_foods/new'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  get 'public_recipes', to: 'recipes#public_recipes'

  resources :foods
  resources :users
  resources :shopping_lists
  resources :recipes do
    member do
      patch 'toggle', to: 'recipes#toggle_recipe'
    end
    resources :recipe_foods
  end
  root "recipes#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    can :read, Recipe, public: true
    can :manage, Recipe, user_id: user.id
    can :manage, Food, user_id: user.id
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :recipes, through: :recipe_foods

  validates :name, presence: true, uniqueness: { case_sensitive: false }
  validates :measurement_unit, presence: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :quantity, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :foods, through: :recipe_foods

  scope :recent_public, -> { where(public: true).order(created_at: :desc) }

  validates :name, :description, :preparation_time, :cooking_time, presence: true
  validates :preparation_time, :cooking_time, numericality: { greater_than_or_equal_to: 0 }
  validates :public, inclusion: { in: [true, false] }
  validates :name, uniqueness: true

  def total_price
    recipe_foods.joins(:food).sum('foods.price * recipe_foods.quantity')
  end
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food

  validates :quantity, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :recipes, dependent: :destroy
  has_many :foods, dependent: :destroy

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery prepend: true
  before_action :configure_permitted_parameters, if: :devise_controller?

  rescue_from CanCan::AccessDenied do |exception|
    respond_to do |format|
      format.json { head :forbidden, content_type: 'text/html' }
      format.html { redirect_to main_app.root_url, alert: exception.message }
      format.js { head :forbidden, content_type: 'text/html' }
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  load_and_authorize_resource

  def index
    @foods = Food.all
  end

  def show; end

  def new
    @food = Food.new
  end

  def create
    @food = current_user.foods.build(food_params)

    respond_to do |format|
      if @food.save
        format.html { redirect_to foods_url, notice: 'Food was successfully created.' }
        format.json { render :index, status: :created, location: @food }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit; end

  def update; end

  def destroy
    @food.destroy
    respond_to do |format|
      format.html { redirect_to foods_url, notice: 'Food was successfuly deleted' }
      format.json { head :no_content }
    end
  end

  private

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity)
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  def new
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = RecipeFood.new
    @foods = Food.all
  end

  def create
    @recipe = Recipe.find(params[:recipe_id])
    @food = Food.find(params[:recipe_food][:food_id])
    @recipe_food = @recipe.recipe_foods.new(food: @food, recipe: @recipe,
                                            quantity: params[:recipe_food][:quantity])
    if @recipe_food.save
      redirect_to recipe_path(@recipe), notice: 'Food was successfully added to the recipe.'

    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = RecipeFood.find(params[:id])
    @recipe_food.delete
    redirect_to @recipe
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[destroy]
  load_and_authorize_resource
  before_action :authenticate_user!, except: [:public_recipes]

  # GET /recipes or /recipes.json
  def index
    @recipes = current_user.recipes
  end

  # GET /recipes/1 or /recipes/1.json
  def show
    @recipe = Recipe.includes(:foods).find(params[:id])
    @recipe_foods = @recipe.recipe_foods.includes(:food)
    @foods = Food.all
  end

  # GET /recipes/new
  def new
    @recipe = current_user.recipes.build
  end

  # POST /recipes or /recipes.json
  def create
    @recipe = current_user.recipes.build(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to recipe_url(@recipe), notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    if @recipe.destroy
      redirect_to recipes_url, notice: 'Recipe was successfully destroyed'
    else
      redirect_to recipes_url, alert: 'You cannot delete this recipe'
    end
  end

  def toggle_recipe
    @recipe = current_user.recipes.find(params[:id])
    @recipe.update(public: !@recipe.public)
    redirect_to @recipe, notice: 'Recipe status toggled successfully.'
  end

  def public_recipes
    @recent_public_recipes = Recipe.recent_public.includes(:user)
  end

  private

  def set_recipe
    @recipe = if params[:id] == 'public_recipes'
                # No need to find a recipe when displaying public recipes
                nil
              else
                # Find the recipe by its id
                current_user.recipes.find(params[:id])
              end
  end

  # Only allow a list of trusted parameters through.
  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public, :user_id)
  end
end

app/controllers/shopping_list_controller.rb
class ShoppingListController < ApplicationController
end

app/controllers/shopping_lists_controller.rb
class ShoppingListsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user_data

  def index
    @shopping_list = calculate_general_shopping_list
  end

  private

  def set_user_data
    @recipes = Recipe.all
    @recipes_food = @recipes.flat_map(&:recipe_foods)
    @foods = Food.all
  end

  def calculate_general_shopping_list
    shopping_list = []

    @foods.each do |food|
      recipe_food_items = @recipes_food.select { |rf| rf.food_id == food.id }
      total_recipe_quantity = recipe_food_items.sum(&:quantity)
      total_user_quantity = food.quantity

      if total_recipe_quantity > total_user_quantity
        difference = total_recipe_quantity - total_user_quantity
        shopping_list << { food_name: food.name, difference:, price: food.price }
      end
    end

    shopping_list
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/shopping_list_helper.rb
module ShoppingListHelper
end

app/helpers/shopping_lists_helper.rb
module ShoppingListsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/foods/_form.html.erb
<%= form_with(model: @food, url: foods_path, local: true, class: 'needs-validation', novalidate: true) do |form| %>
  <% if @food.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <h4 class="alert-heading"><%= pluralize(@food.errors.count, "error") %> prohibited this food from being saved:</h4>
      <ul>
        <% @food.errors.each do |error| %>
          <li><%= error.full_message %></li> 
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-6">
        <div class="mb-3">
          <%= form.label :name %>
          <%= form.text_field :name, class: 'form-control' %>
        </div>

        <div class="mb-3">
          <%= form.label :measurement_unit %>
          <%= form.text_field :measurement_unit, class: 'form-control' %>
        </div>

        <div class="mb-3">
          <%= form.label :price %>
          <%= form.text_field :price, class: 'form-control' %>
        </div>

        <div class="mb-3">
          <%= form.label :quantity %>
          <%= form.text_field :quantity, class: 'form-control' %>
        </div>

        <div class="mb-3">
          <%= form.submit class: 'btn btn-primary' %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/foods/index.html.erb
<div class="container mt-3">
<%= link_to "Add Food", new_food_path, class: "btn btn-primary mb-3 float-right" %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">Food</th>
        <th scope="col">Measurement unit</th>
        <th scope="col">Unit price</th>
        <th scope="col">Quantity</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @foods.each do |food| %>
        <tr>
          <td><%= food.name %></td>
          <td><%= food.measurement_unit %></td>
          <td><%= number_to_currency(food.price) %></td>
          <td><%= food.quantity %></td>
          <td>
            <% if can? :destroy, food %>
              <%= button_to 'Delete', food_path(food), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/foods/new.html.erb
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-lg-8">
      <h1 class="mb-4 text-center">Add Food</h1>
      <%= render "form", food: @food %>
      <div class="mt-4 text-center">
        <%= link_to "Back to foods", foods_path, class: "btn btn-secondary" %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<% if user_signed_in? %>
<footer class="footer bg-dark text-white pt-3 pb-3">
  <div class="container">
    <div class="row">
      <div class="col-lg-6 col-md-8 mb-3">
        <h5>Connect with us</h5>
        <!-- Author 1: Julio Quezada -->
        <div class="mb-2">
          <span class="footer-author-name">Julio Quezada</span>
          <a href="https://github.com/Alejandroq12" target="_blank" class="text-white me-2"><i class="fab fa-github fa-lg"></i></a>
          <a href="https://twitter.com/JulioAle54" target="_blank" class="text-white me-2"><i class="fab fa-twitter fa-lg"></i></a>
          <a href="https://www.linkedin.com/in/quezadajulio/" target="_blank" class="text-white me-2"><i class="fab fa-linkedin fa-lg"></i></a>
          <a href="http://www.quezadajulio.com" target="_blank" class="text-white me-2"><i class="fas fa-globe fa-lg"></i></a>
        </div>
        <!-- Author 2: Nessrine Macherki -->
        <div>
          <span class="footer-author-name">Nessrine Macherki</span>
          <a href="https://github.com/Nessrine88" target="_blank" class="text-white me-2"><i class="fab fa-github fa-lg"></i></a>
          <a href="https://www.linkedin.com/in/nessrine-macherki-86959196/" target="_blank" class="text-white"><i class="fab fa-linkedin fa-lg"></i></a>
        </div>
      </div>
      
      <div class="col-lg-6 col-md-4 text-center text-md-right">
        <h5>RecipeApp</h5>
        <p>© 2024 RecipeApp. All rights reserved.</p>
        <p>Made by Julio Quezada & Nessrine Macherki</p>
      </div>
    </div>
  </div>
</footer>
<% end %>

app/views/layouts/_navbar.html.erb
<% if user_signed_in? %>
<nav class="navbar navbar-expand-md navbar-light bg-dark py-2">
  <div class="container-fluid">
    <a class="navbar-brand" href="<%= root_path %>"><%= image_tag('logo.png', alt: 'Logo') %></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link nav-link-large <%= 'fw-bold p-2 rounded text-danger shadow-lg active-link' if current_page?(recipes_path) %> <%= 'text-light' unless current_page?(recipes_path) %>" href="<%= recipes_path %>">Recipe List</a>
        </li>
        <li class="nav-item">
          <a class="nav-link nav-link-large <%= 'fw-bold p-2 rounded text-danger shadow-lg active-link' if current_page?(public_recipes_path) %> <%= 'text-light' unless current_page?(public_recipes_path) %>" href="<%= public_recipes_path %>">Public Recipes</a>
        </li>
        <li class="nav-item">
          <a class="nav-link nav-link-large <%= 'fw-bold p-2 rounded text-danger shadow-lg active-link' if current_page?(foods_path) %> <%= 'text-light' unless current_page?(foods_path) %>" href="<%= foods_path %>">Food List</a>
        </li>
        <li class="nav-item">
          <a class="nav-link nav-link-large <%= 'fw-bold p-2 rounded text-danger shadow-lg active-link' if current_page?(new_food_path) %> <%= 'text-light' unless current_page?(new_food_path) %>" href="<%= new_food_path %>">New Food</a>
        </li>
        <li class="nav-item">
          <%= button_to "Logout", destroy_user_session_path, method: :delete, class: "btn btn-outline-secondary nav-link-large text-light", form_class: "d-inline" %>
        </li>
      </ul>
    </div>
  </div>
</nav>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload", media: "all" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <p class="notice"><%= notice %></p>
    <% unless controller_name == 'sessions' && action_name == 'new' || controller_name == 'registrations'%>
      <p class="alert"><%= alert %></p>
    <% end %>
    <%= yield %>
    <%= render "layouts/footer" %>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

app/views/recipe_foods/new.html.erb
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-lg-6">
      <h1 class="mb-4 text-center">Add Food to Recipe</h1>
      <%= form_with(model: @recipe_food, url: recipe_recipe_foods_path(@recipe), local: true) do |form| %>
        <div class="input-group mb-3">
          <%= form.label :food_id, class: "input-group-text" %>
          <%= form.select :food_id, @foods.uniq.map { |key| [key.name, key.id] }, {}, { class:"form-select" } %>
        </div>
        <div class="mb-3">
          <%= form.label :quantity, class: 'form-label' %>
          <%= form.number_field :quantity, class: 'form-control', required: true %>
        </div>
        <div class="text-center">
          <%= form.submit 'Create Food', class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/recipes/_form.html.erb
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-8"> <!-- Adjust this value to control form width -->
      <h1 class="text-center mb-4">New Recipe</h1>

      <%= form_with(model: recipe, local: true) do |form| %>
        <% if recipe.errors.any? %>
          <div class="alert alert-danger" role="alert">
            <h4><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h4>
            <ul>
              <% recipe.errors.each do |error| %>
                <li><%= error.full_message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="mb-3">
          <%= form.label :name %>
          <%= form.text_field :name, class: "form-control" %>
        </div>

        <div class="mb-3">
          <%= form.label :preparation_time %>
          <%= form.number_field :preparation_time, class: "form-control" %>
        </div>

        <div class="mb-3">
          <%= form.label :cooking_time %>
          <%= form.number_field :cooking_time, class: "form-control" %>
        </div>

        <div class="mb-3">
          <%= form.label :description %>
          <%= form.text_area :description, class: "form-control" %>
        </div>

        <div class="mb-3 form-check">
          <%= form.check_box :public, class: "form-check-input" %>
          <%= form.label :public, class: "form-check-label" %>
        </div>

        <div class="text-center">
          <%= form.submit 'Create Food', class: 'btn btn-primary' %>
        </div>
      <% end %>

      <div class="text-center mt-4">
        <%= link_to "Back to recipes", recipes_path, class: "btn btn-secondary" %>
      </div>
    </div>
  </div>
</div>

app/views/recipes/index.html.erb
<p class="text-center text-success"><%= notice %></p>

<h1 class="text-center">Recipes</h1>

<div class="container">
  <div id="recipes" class="row justify-content-center">
    <% @recipes.each do |recipe| %>
      <div id="<%= dom_id recipe %>" class="col-md-10 col-lg-10 mb-4 d-flex align-items-stretch">
        <div class="card w-100">
          <div class="card-body">
            <h5 class="card-title text-center"><%= link_to recipe.name, recipe %></h5>
            <p class="card-text"><%= recipe.description %></p>
            <% if can? :destroy, recipe %>
              <%= button_to 'Remove', recipe_path(recipe), method: :delete, data: { confirm: 'Are you sure' }, class: "btn btn-danger w-100" %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

<div class="text-center mt-4 mb-5">
  <%= link_to "New recipe", new_recipe_path, class: "btn btn-primary" %>
</div>

app/views/recipes/new.html.erb
<div class="container mt-5">
  <%= render "form", recipe: @recipe %>
</div>

app/views/recipes/public_recipes.html.erb
<h1 class="text-center mb-4">Public Recipes</h1>

<div class="container">
  <div class="row justify-content-center">
    <% @recent_public_recipes.each do |recipe| %>
      <div class="col-md-10 col-lg-10 mb-4">
        <div class="card">
          <div class="card-body">
            <h2 class="card-title"><%= link_to recipe.name, recipe %></h2>
            <p class="card-text">By: <%= recipe.user.name %></p>
            <p class="card-text">Total food items: <%= recipe.recipe_foods.size %></p>
            <p class="card-text">Total price: $<%= recipe.total_price %></p>
            <% if can? :destroy, recipe %>
              <%= button_to 'Remove', recipe_path(recipe), method: :delete, data: { confirm: 'Are you sure' }, class: "btn btn-danger mt-2 w-100" %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/recipes/show.html.erb
<div class="container p-5">
  <div class="row">
    <div class= "col">
      <p><%= notice %></p>
          <p><strong>Name:</strong> <%= @recipe.name %></p>
          <p><strong>Preparation time:</strong> <%= @recipe.preparation_time %>h</p>
          <p><strong>Cooking time:</strong> <%= @recipe.cooking_time %>h</p>
          <p><strong>Description:</strong> <%= @recipe.description %></p>
          </div>

    <div class="col pt-5 d-flex alig-items-end">
          <% if @recipe.user_id == current_user.id %>
            <%= form_with model: @recipe, url: toggle_recipe_path(@recipe), method: :patch, local: true do |form| %>
              <label class="switch">
                Public:
                <div class="toggle_status_container">
                  <input type="submit" class="btn-check toggle-button <%= @recipe.public ? 'btn-success' : 'btn-danger' %>" id="btn-check-2-outlined" checked autocomplete="off">
                  <label id="label" class="btn <%= @recipe.public ? 'btn-outline-success' : 'btn-outline-danger' %>" for="btn-check-2-outlined"><%= @recipe.public %></label><br>
                </div>
              </label>
            <% end %>
          <% end %>
          </div>
      </div>
      </div>
      <div class="container">
      <div class="row">
      <div class="col">
      <%= link_to "Generate Shopping List", shopping_lists_path, class: "btn btn-warning gen" %>
        </div>
        <div class="col">
        <% if current_user.id == @recipe.user_id %>
          <%= link_to "Add Ingredient", new_recipe_recipe_food_path(@recipe), class: 'btn btn-primary' %>
        <% end %>
      </div>
      </div>
    </div>
   
  </div>
 
  </div>

  <div class="row mt-5">
    <div class="col-md-8 offset-md-2">
      <div class="d-block mx-auto w-100">
        <table class="table table-striped table-bordered ">
          <thead>
            <tr>
              <th scope="col">Food</th>
              <th scope="col">Quantity</th>
              <th scope="col">Value</th>
              <th scope="col">Action</th>
            </tr>
          </thead>
          <tbody>
            <% @recipe_foods.each do |recipe_food| %>
              <tr>
                <td><%= recipe_food.food.name %></td>
                <td><%= recipe_food.quantity %></td>
                <td><%= recipe_food.quantity * recipe_food.food.price %></td>
                <td>
                  <% if current_user.id == @recipe.user_id %>
                    <%= form_with model: recipe_food, url: recipe_recipe_food_path(@recipe.id, recipe_food.id), method: :delete, local: false do |f| %>
                      <%= f.hidden_field :food_id, value: "1" %>
                      <%= f.submit "Delete", class: "btn btn-danger btn-sm" %>
                    <% end %>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>

app/views/shopping_list/index.html.erb
<h1>Here is the shopping list</h1>

app/views/shopping_lists/index.html.erb
<h1 align="center" class="p-5">General Shopping List</h1>
<p align="center" class="p-1">
  Please note that when your shopping list is generated, it accounts for all the foods needed
  in each recipe, including both private and public recipes that belong to other users.
  This approach is because the app is designed to manage the food needs of a single restaurant,
  considering all users and their recipes, both public and private.
  This ensures that all foods needed by the restaurant are included.
</p>
<div class="d-flex justify-content-around align-items-center">
<% if @shopping_list.present? %>
<p>Total Food Items to Buy: <%= @shopping_list.size %></p>
<p>Total Value of Food Needed: $<%= @shopping_list.sum { |item| item[:difference] * item[:price] } %></p>
<% else %>
<p>No missing items. Your food is well-stocked!</p>
<% end %>
</div>
<div class="m-5">
  <table class="table table-striped table-bordered">
    <thead>
      <tr>
        <th>Food</th>
        <th>Quantity</th>
        <th>Price</th>
      </tr>
    </thead>
    <tbody>
      <% @shopping_list.each do |item| %>
        <tr>
          <td><%= item[:food_name] %></td>
          <td><%= item[:difference] %></td>
          <td><%= item[:difference] * item[:price] %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  </div>